#
# Makefile for the Atheros ar9331 i2s driver
#
ath79-pcm-mbox-objs := ath79-pcm.o ath79-mbox.o

obj-$(CONFIG_AR9331_PCM)		+= ath79-pcm-mbox.o
obj-$(CONFIG_AR9331_I2S)		+= ath79-i2s.o
obj-$(CONFIG_AR9331_I2S_DEV)	+= dev-audio.o
obj-$(CONFIG_AR9331_WM8727)		+= wm8727.o
obj-$(CONFIG_AR9331_CARAMBOLA2)	+= ath-carambola2.o
